### ISSUE TITLE
can i use it in IE8, chrome,and firefox ?

### ISSUE THREAD

**Issue by yvonnegithub** [feross/clipboard-copy#8] opened 2017-09-08 04:10 UTC

**Comment by LinusU** [comment] 2018-01-27 12:08
Chrome and Firefox are supported.

IE support was merged in #9, but I'm not sure which version.

We should check and add it to the readme, PRs welcome 🙌

**Comment by feross** [comment] 2018-02-03 05:23
The point of this library (versus other ones mentioned in the readme) is to be lightweight. We only support modern browsers. I was okay with adding IE support in #9 since it didn't add new lines of code or hacks.

I'll test in IE11 just to confirm it works, add that to the readme, and then close this issue.

**Comment by feross** [comment] 2018-02-03 05:31
Great, confirmed it works in IE11. ✨

Let's not support anything lower, the other libraries already work for that!

**Closed as completed by feross** 2018-02-03 05:31 UTC
Labels: help wanted, good first issue
